spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml